### ISSUE TITLE
[Syntax highlighting] Fails to recognize implementing multiple interfaces

### ISSUE THREAD

**Issue by KamasamaK** [kuniss/xtend-ide-extensions#1]
I have a class that implements multiple interfaces, but the syntax highlighting is erroneously showing it as invalid. Specifically, the second interface is assigned the `invalid.illegal.Xtend` scope from the grammar.

![image](https://user-images.githubusercontent.com/22951521/95586965-6fb74100-0a0f-11eb-9747-76226e4b64e4.png)

**Comment by kuniss** [comment]
Thanks for the report. I will try to have a look on that. Hopefully next week.

**Comment by kuniss** [comment]
@KamasamaK 
Can you give me some context, please? Where does it show the wrong highlighting - VS code, Gitpod or where?
Which theme are you using?
It's definitely wrong. But I see the invalid highlighting only in Iro, not in VS code. I did not try to reproduce it on Gitpod yet.

**Comment by KamasamaK** [comment]
@kuniss This is occurring in VS Code 1.50.0 for me. The theme I am using is `Dark+`.

**Comment by kuniss** [comment]
@KamasamaK Solved. But please be patient. I need some time to publish it. Planned long time ago to automate this. This is the opportunity. :smile:

**Comment by kuniss** [comment]
Solved with version 0.2.2 of [VS Code extension](https://marketplace.visualstudio.com/items?itemName=Grammarcraft.xtend-lang) and [OVSX](https://open-vsx.org/extension/grammarcraft/xtend-lang) extension.
